"""AI Strategic Summary, Policy Governance, and Observability rendering (Issue #53)."""

from __future__ import annotations


def get_ai_html() -> str:
    """Returns HTML markup for #view-ai_insights."""
    return '    <!-- VIEW: AI INSIGHTS (AI 分析) -->\n    <section class="view-container" id="view-ai_insights">\n      <div class="section-header">\n        <div>\n          <h2 class="section-title">AI 分析與行動建議 (AI Insights)</h2>\n          <div class="section-subtitle">Gemini 深入分析、分佈洞察與建議行動清單</div>\n        </div>\n      </div>\n\n      <div class="ai-summary-card">\n        <div class="ai-header">\n          <div class="ai-title">AI 策略摘要</div>\n          <span class="ai-model-tag" id="aiFullModelTag">Gemini Flash</span>\n        </div>\n        <p class="ai-overview-text" id="aiFullOverviewText"></p>\n        <div class="ai-takeaways-list" id="aiFullTakeawaysList"></div>\n        <div style="margin-top:12px;font-size:13px;color:var(--text-main);background:var(--bg-surface);border:1px solid var(--border);border-radius:var(--radius-md);padding:12px 14px">\n          <b>分佈洞察：</b> <span id="aiDistributionInsights"></span>\n        </div>\n      </div>\n\n      <div class="table-container" style="margin-top:16px">\n        <div class="table-toolbar">\n          <div class="section-title" style="font-size:14px">推薦行動清單 (Recommended Actions)</div>\n        </div>\n        <table class="data-table">\n          <thead>\n            <tr>\n              <th>優先級</th>\n              <th>目標 Issue</th>\n              <th>建議行動</th>\n              <th>預估工作量</th>\n            </tr>\n          </thead>\n          <tbody id="recommendedActionsTableBody"></tbody>\n        </table>\n      </div>\n    </section>\n\n'


def get_ai_js() -> str:
    """Returns JavaScript rendering function for AI summary."""
    return 'function renderAISummaries() {\n  const app = getCurAppData();\n  if (!app) return;\n  const snap = getCurPeriodSnapshot();\n  const ai = snap?.ai_summary || app.ai_summary || {};\n\n  const aiSrc = (app.sources && (app.sources.ai || app.sources.gemini_ai)) || {};\n  let modelText = ai.model || "Gemini Flash";\n  if (aiSrc.requested_mode) {\n    modelText += ` (${aiSrc.requested_mode})`;\n  }\n  if (aiSrc.fallback_used) {\n    modelText += " [Fallback]";\n  }\n  $("aiModelTag").textContent = modelText;\n  $("aiFullModelTag").textContent = modelText;\n\n  const overview = ai.overview || "尚無 AI 策略分析。";\n  $("aiOverviewText").textContent = overview;\n  $("aiFullOverviewText").textContent = overview;\n\n  const takeaways = ai.key_takeaways || [];\n  const takeawaysHtml = takeaways.map(t =>\n    `<div class="ai-takeaway-item">\n      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="2.5" style="flex-shrink:0;margin-top:2px"><polyline points="20 6 9 17 4 12"/></svg>\n      <span>${esc(t)}</span>\n    </div>`\n  ).join("");\n\n  $("aiTakeawaysList").innerHTML = takeawaysHtml;\n  $("aiFullTakeawaysList").innerHTML = takeawaysHtml;\n  $("aiDistributionInsights").textContent = ai.distribution_insights || "—";\n\n  // Recommended actions\n  const actions = ai.recommended_actions || [];\n  const actBody = $("recommendedActionsTableBody");\n  if (actions.length) {\n    actBody.innerHTML = actions.map(act => `\n      <tr>\n        <td><span class="badge badge-${(act.priority || "p2").toLowerCase()}">${esc(act.priority)}</span></td>\n        <td class="mono-num">${esc(act.issue_id)}</td>\n        <td><b>${esc(act.action)}</b></td>\n        <td><span class="badge" style="background:var(--bg-subtle)">工作量 ${esc(act.effort || "?")}</span></td>\n      </tr>\n    `).join("");\n  } else {\n    actBody.innerHTML = `<tr><td colspan="4" class="empty-state">尚無推薦行動</td></tr>`;\n  }\n}\n'
